### ISSUE TITLE
Add max-width to GitHub contributions calendar

### ISSUE THREAD

**Issue by 2016rshah** [YourMobileGeek/yourmobilegeek-portfolio#1]
![screenshot_20170711-080206](https://user-images.githubusercontent.com/6821244/28067447-5c4d8ed2-660f-11e7-9dd4-df462cc0dbf3.png)

The GitHub contributions calendar goes off the screen on mobile so if you just add a max-width attribute or something the image should scale properly. Cheers!

**Comment by YourMobileGeek** [comment]
@2016rshah: Ah thank you for this! , I actually had this listed as a to - do on my calendar to complete today. I'll go ahead & make this change today!
